FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends python3 make g++

COPY package*.json ./
RUN npm install --production

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]