FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ libssl1.1

COPY package*.json ./
RUN npm install --production

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]